<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>AquaHome.Worker</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Share\FishLover.Shared\FishLover.Shared.csproj" />
        <ProjectReference Include="..\AquaHome.Common\AquaHome.Common.csproj" />
        <ProjectReference Include="..\AquaHome.Domain\AquaHome.Domain.csproj" />
        <ProjectReference Include="..\AquaHome.EFCore\AquaHome.EFCore.csproj" />
    </ItemGroup>

</Project>
