// <auto-generated />
using System;
using FishDex.EFCore.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FishDex.EFCore.Migrations
{
    [DbContext(typeof(FishDexDbContext))]
    [Migration("20260522074035_AddCommonName")]
    partial class AddCommonName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.Associations", b =>
                {
                    b.Property<int>("AssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssociationId"));

                    b.Property<string>("AssociationRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssociationsRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssociationsWith")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Commensalism")
                        .HasColumnType("boolean");

                    b.Property<int>("EcologyId")
                        .HasColumnType("integer");

                    b.Property<bool>("Epiphytic")
                        .HasColumnType("boolean");

                    b.Property<string>("IHRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InsideHost")
                        .HasColumnType("boolean");

                    b.Property<bool>("Mutualism")
                        .HasColumnType("boolean");

                    b.Property<string>("OHRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OutsideHost")
                        .HasColumnType("boolean");

                    b.Property<bool>("Parasitism")
                        .HasColumnType("boolean");

                    b.Property<string>("SchoolShoalRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Schooling")
                        .HasColumnType("boolean");

                    b.Property<string>("SchoolingFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolingLifestage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Shoaling")
                        .HasColumnType("boolean");

                    b.Property<string>("ShoalingFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShoalingLifestage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Solitary")
                        .HasColumnType("boolean");

                    b.Property<bool>("Symbiosis")
                        .HasColumnType("boolean");

                    b.Property<bool>("Symphorism")
                        .HasColumnType("boolean");

                    b.HasKey("AssociationId");

                    b.HasIndex("EcologyId")
                        .IsUnique();

                    b.ToTable("Associations");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.CircadianBehavior", b =>
                {
                    b.Property<int>("CircadianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CircadianId"));

                    b.Property<string>("BioAspect1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BioAspect2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BioAspect3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Circadian1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Circadian2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Circadian3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CircadianAlsoRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CircadianRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EcologyId")
                        .HasColumnType("integer");

                    b.Property<string>("RemarksCircadian")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CircadianId");

                    b.HasIndex("EcologyId")
                        .IsUnique();

                    b.ToTable("CircadianBehaviors");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.Ecology", b =>
                {
                    b.Property<int>("EcologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EcologyId"));

                    b.Property<DateTime>("Datechecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Dateentered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Datemodified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EcologyRefNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entered")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Expert")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modified")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpecCode")
                        .HasColumnType("integer");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TS")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("autoctr")
                        .HasColumnType("integer");

                    b.HasKey("EcologyId");

                    b.HasIndex("SpecCode");

                    b.ToTable("Ecologies");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.FeedingAndDiet", b =>
                {
                    b.Property<int>("FeedingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedingId"));

                    b.Property<string>("AddRems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DietRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DietRemark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DietSeTroph")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DietTLu")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DietTroph")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DietseTLu")
                        .HasColumnType("numeric");

                    b.Property<int>("EcologyId")
                        .HasColumnType("integer");

                    b.Property<string>("FeedingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedingTypeRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FoodRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FoodRemark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FoodSeTroph")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FoodTroph")
                        .HasColumnType("numeric");

                    b.Property<bool>("Herbivory2")
                        .HasColumnType("boolean");

                    b.Property<string>("HerbivoryRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FeedingId");

                    b.HasIndex("EcologyId")
                        .IsUnique();

                    b.ToTable("FeedingAndDiets");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.HabitatZone", b =>
                {
                    b.Property<int>("HabitatZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HabitatZoneId"));

                    b.Property<bool>("Abyssopelagic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Bathypelagic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Cave")
                        .HasColumnType("boolean");

                    b.Property<bool>("Cave2")
                        .HasColumnType("boolean");

                    b.Property<bool>("CaveAnchialine")
                        .HasColumnType("boolean");

                    b.Property<bool>("Caves")
                        .HasColumnType("boolean");

                    b.Property<int>("EcologyId")
                        .HasColumnType("integer");

                    b.Property<bool>("Epipelagic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estuaries")
                        .HasColumnType("boolean");

                    b.Property<string>("HabitatsRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Hadopelagic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Intertidal")
                        .HasColumnType("boolean");

                    b.Property<bool>("Lakes")
                        .HasColumnType("boolean");

                    b.Property<bool>("LittoralZone")
                        .HasColumnType("boolean");

                    b.Property<bool>("Mangroves")
                        .HasColumnType("boolean");

                    b.Property<bool>("MarshesSwamps")
                        .HasColumnType("boolean");

                    b.Property<bool>("Mesopelagic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Neritic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Oceanic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Saltmarshes")
                        .HasColumnType("boolean");

                    b.Property<bool>("Stream")
                        .HasColumnType("boolean");

                    b.Property<bool>("SubLittoral")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupraLittoralZone")
                        .HasColumnType("boolean");

                    b.Property<bool>("TidePools")
                        .HasColumnType("boolean");

                    b.HasKey("HabitatZoneId");

                    b.HasIndex("EcologyId")
                        .IsUnique();

                    b.ToTable("HabitatZones");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.SpecialHabitat", b =>
                {
                    b.Property<int>("SpecialHabitatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecialHabitatId"));

                    b.Property<bool>("BedsBivalve")
                        .HasColumnType("boolean");

                    b.Property<bool>("BedsOthers")
                        .HasColumnType("boolean");

                    b.Property<bool>("BedsRock")
                        .HasColumnType("boolean");

                    b.Property<bool>("BetweenPolyps")
                        .HasColumnType("boolean");

                    b.Property<bool>("BoatHulls")
                        .HasColumnType("boolean");

                    b.Property<bool>("Burrows")
                        .HasColumnType("boolean");

                    b.Property<bool>("ColdSeeps")
                        .HasColumnType("boolean");

                    b.Property<bool>("CoralReefs")
                        .HasColumnType("boolean");

                    b.Property<bool>("Corals")
                        .HasColumnType("boolean");

                    b.Property<bool>("Crevices")
                        .HasColumnType("boolean");

                    b.Property<bool>("DeepWaterCorals")
                        .HasColumnType("boolean");

                    b.Property<bool>("Driftwood")
                        .HasColumnType("boolean");

                    b.Property<bool>("DropOffs")
                        .HasColumnType("boolean");

                    b.Property<int>("EcologyId")
                        .HasColumnType("integer");

                    b.Property<bool>("Guyots")
                        .HasColumnType("boolean");

                    b.Property<bool>("HardCorals")
                        .HasColumnType("boolean");

                    b.Property<bool>("HydrothermalVents")
                        .HasColumnType("boolean");

                    b.Property<bool>("InterstitialSpaces")
                        .HasColumnType("boolean");

                    b.Property<bool>("Lagoons")
                        .HasColumnType("boolean");

                    b.Property<bool>("Leaves")
                        .HasColumnType("boolean");

                    b.Property<bool>("Macrophyte")
                        .HasColumnType("boolean");

                    b.Property<string>("OIRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OInverterbrates")
                        .HasColumnType("boolean");

                    b.Property<bool>("OnExoskeleton")
                        .HasColumnType("boolean");

                    b.Property<bool>("OnPolyp")
                        .HasColumnType("boolean");

                    b.Property<bool>("Pilings")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReefExclusive")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReefFlats")
                        .HasColumnType("boolean");

                    b.Property<bool>("RicePaddies")
                        .HasColumnType("boolean");

                    b.Property<bool>("Roots")
                        .HasColumnType("boolean");

                    b.Property<bool>("SeaGrassBeds")
                        .HasColumnType("boolean");

                    b.Property<bool>("Seamounts")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoftCorals")
                        .HasColumnType("boolean");

                    b.Property<string>("SpecialHabitatRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Stems")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tunnels")
                        .HasColumnType("boolean");

                    b.Property<string>("VRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Vegetation")
                        .HasColumnType("boolean");

                    b.Property<bool>("Verterbrates")
                        .HasColumnType("boolean");

                    b.HasKey("SpecialHabitatId");

                    b.HasIndex("EcologyId")
                        .IsUnique();

                    b.ToTable("SpecialHabitats");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.Substrate", b =>
                {
                    b.Property<int>("SubstrateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubstrateId"));

                    b.Property<bool>("Benthic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Coarse")
                        .HasColumnType("boolean");

                    b.Property<bool>("Demersal")
                        .HasColumnType("boolean");

                    b.Property<bool>("Detritus")
                        .HasColumnType("boolean");

                    b.Property<int>("EcologyId")
                        .HasColumnType("integer");

                    b.Property<bool>("Endofauna")
                        .HasColumnType("boolean");

                    b.Property<bool>("Fine")
                        .HasColumnType("boolean");

                    b.Property<bool>("Gravel")
                        .HasColumnType("boolean");

                    b.Property<bool>("HardBottom")
                        .HasColumnType("boolean");

                    b.Property<bool>("Level")
                        .HasColumnType("boolean");

                    b.Property<bool>("Macrobenthos")
                        .HasColumnType("boolean");

                    b.Property<bool>("Megabenthos")
                        .HasColumnType("boolean");

                    b.Property<bool>("Meiobenthos")
                        .HasColumnType("boolean");

                    b.Property<bool>("Mobile")
                        .HasColumnType("boolean");

                    b.Property<bool>("Mud")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ooze")
                        .HasColumnType("boolean");

                    b.Property<bool>("Organic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Pelagic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Rocky")
                        .HasColumnType("boolean");

                    b.Property<bool>("Rubble")
                        .HasColumnType("boolean");

                    b.Property<bool>("Sand")
                        .HasColumnType("boolean");

                    b.Property<bool>("Sessile")
                        .HasColumnType("boolean");

                    b.Property<bool>("Silt")
                        .HasColumnType("boolean");

                    b.Property<bool>("Sloping")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoftBottom")
                        .HasColumnType("boolean");

                    b.Property<string>("SubstrateRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubstrateId");

                    b.HasIndex("EcologyId")
                        .IsUnique();

                    b.ToTable("Substrates");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecosystem.Ecosystem", b =>
                {
                    b.Property<int>("AutoCtr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AutoCtr"));

                    b.Property<string>("Abundance")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CurrentPresence")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("Dateentered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Datemodified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("E_CODE")
                        .HasColumnType("integer");

                    b.Property<int?>("EcosystemRefNo")
                        .HasColumnType("integer");

                    b.Property<string>("Entered")
                        .HasColumnType("text");

                    b.Property<string>("LifeStage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modified")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("SpecCode")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("StockCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TS")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AutoCtr");

                    b.HasIndex("E_CODE");

                    b.HasIndex("SpecCode");

                    b.ToTable("Ecosystem");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecosystem.EcosystemRef", b =>
                {
                    b.Property<int>("E_CODE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("E_CODE"));

                    b.Property<double?>("Area")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageDepth")
                        .HasColumnType("double precision");

                    b.Property<bool>("Boreal")
                        .HasColumnType("boolean");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("DrainageArea")
                        .HasColumnType("double precision");

                    b.Property<double?>("EasternLat")
                        .HasColumnType("double precision");

                    b.Property<string>("EcosystemName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EcosystemType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LME")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MEOW")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MPA")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("MaxDepth")
                        .HasColumnType("double precision");

                    b.Property<double?>("NorthernLat")
                        .HasColumnType("double precision");

                    b.Property<bool>("Polar")
                        .HasColumnType("boolean");

                    b.Property<double?>("RiverLength")
                        .HasColumnType("double precision");

                    b.Property<double?>("Salinity")
                        .HasColumnType("double precision");

                    b.Property<double?>("SouthernLat")
                        .HasColumnType("double precision");

                    b.Property<bool>("Subtropical")
                        .HasColumnType("boolean");

                    b.Property<double?>("TempDepth")
                        .HasColumnType("double precision");

                    b.Property<double?>("TempSurface")
                        .HasColumnType("double precision");

                    b.Property<bool>("Temperate")
                        .HasColumnType("boolean");

                    b.Property<int?>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalFamCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Tropical")
                        .HasColumnType("boolean");

                    b.Property<double?>("WesternLat")
                        .HasColumnType("double precision");

                    b.HasKey("E_CODE");

                    b.ToTable("EcosystemRef");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Media.SystemImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BestPic")
                        .HasColumnType("text");

                    b.Property<string>("LengthType")
                        .HasColumnType("text");

                    b.Property<string>("LifeStage")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("PicPreferred")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PicPreferredFem")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PicPreferredJuv")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PicPreferredMale")
                        .HasColumnType("boolean");

                    b.Property<string>("PictureType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<double?>("Size")
                        .HasColumnType("double precision");

                    b.Property<int>("SpecCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecCode");

                    b.ToTable("SystemImages");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphData", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("integer");

                    b.Property<string>("AppearancePic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyShapeI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyShapeII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEntered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EaseofID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Entered")
                        .HasColumnType("integer");

                    b.Property<int?>("Expert")
                        .HasColumnType("integer");

                    b.Property<int?>("Females")
                        .HasColumnType("integer");

                    b.Property<string>("Forehead")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GasBladder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Males")
                        .HasColumnType("integer");

                    b.Property<int?>("Modified")
                        .HasColumnType("integer");

                    b.Property<string>("MorphDatRefNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperculumPresent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PosofMouth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemarkSex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SexMorphology")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SexualAttributes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Speccode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TS")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TypeofEyes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeofMouth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StockCode");

                    b.ToTable("MorphData");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphFins", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("integer");

                    b.Property<string>("Adifin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Afinno")
                        .HasColumnType("integer");

                    b.Property<string>("AnalFinI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnalFinII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AnalFinSpinesMax")
                        .HasColumnType("integer");

                    b.Property<int?>("AnalFinSpinesMin")
                        .HasColumnType("integer");

                    b.Property<int?>("Araymax")
                        .HasColumnType("integer");

                    b.Property<int?>("Araymin")
                        .HasColumnType("integer");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaudalFinI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaudalFinII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DFinletsmax")
                        .HasColumnType("integer");

                    b.Property<int?>("DFinletsmin")
                        .HasColumnType("integer");

                    b.Property<int?>("Dfinno")
                        .HasColumnType("integer");

                    b.Property<string>("DorsalAttributes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DorsalFinI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DorsalFinII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DorsalSoftRaysMax")
                        .HasColumnType("integer");

                    b.Property<int?>("DorsalSoftRaysMin")
                        .HasColumnType("integer");

                    b.Property<int?>("DorsalSpinesMax")
                        .HasColumnType("integer");

                    b.Property<int?>("DorsalSpinesMin")
                        .HasColumnType("integer");

                    b.Property<string>("Notched")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PectoralAttributes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PelvicsAttributes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Praymax")
                        .HasColumnType("integer");

                    b.Property<int?>("Praymin")
                        .HasColumnType("integer");

                    b.Property<string>("Pspines2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VPosition2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Vraymax")
                        .HasColumnType("integer");

                    b.Property<int?>("Vraymin")
                        .HasColumnType("integer");

                    b.Property<string>("Vspines")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StockCode");

                    b.ToTable("MorphFins");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphMeristics", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("integer");

                    b.Property<int?>("BarbelsNo")
                        .HasColumnType("integer");

                    b.Property<string>("BarbelsType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GillCleftsNo")
                        .HasColumnType("integer");

                    b.Property<int?>("GillRakersLowMax")
                        .HasColumnType("integer");

                    b.Property<int?>("GillRakersLowMin")
                        .HasColumnType("integer");

                    b.Property<int?>("GillRakersTotalMax")
                        .HasColumnType("integer");

                    b.Property<int?>("GillRakersTotalMin")
                        .HasColumnType("integer");

                    b.Property<int?>("GillRakersUpMax")
                        .HasColumnType("integer");

                    b.Property<int?>("GillRakersUpMin")
                        .HasColumnType("integer");

                    b.Property<string>("Keels")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LLinterrupted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LatSeriesMax")
                        .HasColumnType("integer");

                    b.Property<int?>("LatSeriesMin")
                        .HasColumnType("integer");

                    b.Property<int?>("LateralLinesNo")
                        .HasColumnType("integer");

                    b.Property<int?>("PoredScalesMax")
                        .HasColumnType("integer");

                    b.Property<int?>("PoredScalesMin")
                        .HasColumnType("integer");

                    b.Property<int?>("ScaleRowsAboveMax")
                        .HasColumnType("integer");

                    b.Property<int?>("ScaleRowsAboveMin")
                        .HasColumnType("integer");

                    b.Property<int?>("ScaleRowsBelowMax")
                        .HasColumnType("integer");

                    b.Property<int?>("ScaleRowsBelowMin")
                        .HasColumnType("integer");

                    b.Property<int?>("ScalesLateralmax")
                        .HasColumnType("integer");

                    b.Property<int?>("ScalesLateralmin")
                        .HasColumnType("integer");

                    b.Property<int?>("ScalesPeduncMax")
                        .HasColumnType("integer");

                    b.Property<int?>("ScalesPeduncMin")
                        .HasColumnType("integer");

                    b.Property<string>("Scutes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Spiracle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeofScales")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vertebrae")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VertebraePreanMax")
                        .HasColumnType("integer");

                    b.Property<int?>("VertebraePreanMin")
                        .HasColumnType("integer");

                    b.Property<int?>("VertebraeTotalMax")
                        .HasColumnType("integer");

                    b.Property<int?>("VertebraeTotalMin")
                        .HasColumnType("integer");

                    b.HasKey("StockCode");

                    b.ToTable("MorphMeristics");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphMetrics", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("integer");

                    b.Property<string>("AddChars")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("CaudalHeight")
                        .HasColumnType("double precision");

                    b.Property<double?>("EyeLength")
                        .HasColumnType("double precision");

                    b.Property<double?>("Forklength")
                        .HasColumnType("double precision");

                    b.Property<double?>("HeadLength")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaximumDepth")
                        .HasColumnType("double precision");

                    b.Property<string>("OtherRef1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherRef2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("PeduncleDepth")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeduncleLength")
                        .HasColumnType("double precision");

                    b.Property<double?>("PostHeadDepth")
                        .HasColumnType("double precision");

                    b.Property<double?>("PostTrunkDepth")
                        .HasColumnType("double precision");

                    b.Property<double?>("PreAnalLength")
                        .HasColumnType("double precision");

                    b.Property<double?>("PreDorsalLength")
                        .HasColumnType("double precision");

                    b.Property<double?>("PrePelvicsLength")
                        .HasColumnType("double precision");

                    b.Property<double?>("PreorbitalLength")
                        .HasColumnType("double precision");

                    b.Property<string>("SimilarSpec1Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SimilarSpec2Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SimilarSpecies1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SimilarSpecies2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("StandardLengthCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("Totallength")
                        .HasColumnType("double precision");

                    b.HasKey("StockCode");

                    b.ToTable("MorphMetrics");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphPigmentation", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("integer");

                    b.Property<string>("CurStripesTTI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurStripesTTII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurStripesTTIII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiaStripesTTI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiaStripesTTII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiaStripesTTIII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorStripesTTI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorStripesTTII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SexColors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpotsTTI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpotsTTII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpotsTTIII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrikingFeatures")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerStripesTTI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerStripesTTII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerStripesTTIII")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StockCode");

                    b.ToTable("MorphPigmentation");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphTeeth", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("integer");

                    b.Property<string>("CommentonTeeth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DermalTeeth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lipsteeth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MandibleRowsMax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MandibleRowsMin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MandibleTeeth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MandibleTeethT1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MandibleTeethT2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxillaRowsMax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxillaRowsMin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxillaTeeth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxillaTeethT1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxillaTeethT2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Palatine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PalatineRowsMax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PalatineRowsMin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PalatineTeethT1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PalatineTeethT2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PharyngealRowsMax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PharyngealRowsMin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PharyngealTeeth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PharyngealTeethT1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PharyngealTeethT2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeethonTongue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VomerineRowsMax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VomerineRowsMin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VomerineTeeth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VomerineTeethT1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VomerineTeethT2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StockCode");

                    b.ToTable("MorphTeeth");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Occurrence.Occurrence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("Gazetteer")
                        .HasColumnType("text");

                    b.Property<double>("LatitudeDec")
                        .HasColumnType("double precision");

                    b.Property<string>("Locality")
                        .HasColumnType("text");

                    b.Property<double>("LongitudeDec")
                        .HasColumnType("double precision");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<int>("SpecCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecCode");

                    b.ToTable("Occurrences");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Species.CommonName", b =>
                {
                    b.Property<int>("AutoCtr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AutoCtr"));

                    b.Property<string>("ComName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("NameType")
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("SpecCode")
                        .HasColumnType("integer");

                    b.Property<int?>("StockCode")
                        .HasColumnType("integer");

                    b.Property<string>("Transliteration")
                        .HasColumnType("text");

                    b.HasKey("AutoCtr");

                    b.HasIndex("SpecCode");

                    b.HasIndex("Language", "IsPreferred");

                    b.ToTable("CommonNames");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Species.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyShapeI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FamCode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReproductiveGuild")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SwimMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamCode")
                        .IsUnique();

                    b.ToTable("Families");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Species.Genus", b =>
                {
                    b.Property<int>("GenusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenusCode"));

                    b.Property<Guid>("FamId")
                        .HasColumnType("uuid");

                    b.Property<string>("GenusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenusCode");

                    b.HasIndex("FamId");

                    b.ToTable("Genuses");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Species.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AirBreathing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyShapeI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dangerous")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DemersPelag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FamCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("FamId")
                        .HasColumnType("uuid");

                    b.Property<int>("GenusCode")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Length")
                        .HasColumnType("numeric");

                    b.Property<double?>("LengthFemale")
                        .HasColumnType("double precision");

                    b.Property<string>("LifeCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("LongevityWild")
                        .HasColumnType("double precision");

                    b.Property<string>("MaxLengthRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PicPreferredNameF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PicPreferredNameM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpecCode")
                        .HasColumnType("integer");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpeciesRefNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxIssue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Vulnerability")
                        .HasColumnType("integer");

                    b.Property<int?>("VulnerabilityClimate")
                        .HasColumnType("integer");

                    b.Property<int>("WaterType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FamId");

                    b.HasIndex("GenusCode");

                    b.HasIndex("SpecCode")
                        .IsUnique();

                    b.ToTable("Species");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.Stock", b =>
                {
                    b.Property<int>("StockCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockCode"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LocalUnique")
                        .HasColumnType("boolean");

                    b.Property<int>("SpecCode")
                        .HasColumnType("integer");

                    b.Property<string>("StockDefs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StockDefsGeneral")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SynOC")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("StockCode");

                    b.HasIndex("SpecCode");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.StockConservation", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("integer");

                    b.Property<string>("CITES_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CITES_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CITES_Ref")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CITES_Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CMS")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IUCN_Assessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IUCN_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("IUCN_DateAssessed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IUCN_ID")
                        .HasColumnType("integer");

                    b.Property<int?>("IUCN_IDAssess")
                        .HasColumnType("integer");

                    b.Property<bool>("Protected")
                        .HasColumnType("boolean");

                    b.HasKey("StockCode");

                    b.ToTable("StockConservation");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.StockDataAvailability", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("integer");

                    b.Property<string>("Abnorm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Abundance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Allele")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Aquaculture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Aquamaps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Brains")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Broodstock")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Catches")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryComp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ecology")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ecotoxicology")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EggDevelop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EggNursery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eggs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FAOAqua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fecundity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FishSounds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Foods")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FryNursery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeneticStudies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genetics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gillarea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Introductions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LarvDyn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LarvSpeed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Larvae")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LarvalNursery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LengthFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LengthRelations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LengthWeight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatSizes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Maturity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metabolism")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Morphology")
                        .HasColumnType("boolean");

                    b.Property<string>("Occurrence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PopDyn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Predators")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Processing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reproduction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SCRFA_data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sounds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Spawning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strains")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StockCode");

                    b.ToTable("StockDataAvailability");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.StockEnvironment", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("integer");

                    b.Property<string>("BoundingMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoundingRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("DHMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("DHMin")
                        .HasColumnType("double precision");

                    b.Property<double?>("Easternmost")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnvTemp")
                        .HasColumnType("double precision");

                    b.Property<string>("NorthSouthN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NorthSouthS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Northernmost")
                        .HasColumnType("double precision");

                    b.Property<double?>("PHMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("PHMin")
                        .HasColumnType("double precision");

                    b.Property<int?>("Resilience")
                        .HasColumnType("integer");

                    b.Property<string>("ResilienceRemark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Southermost")
                        .HasColumnType("double precision");

                    b.Property<double?>("TempMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("TempMin")
                        .HasColumnType("double precision");

                    b.Property<double?>("TempPref25")
                        .HasColumnType("double precision");

                    b.Property<double?>("TempPref50")
                        .HasColumnType("double precision");

                    b.Property<double?>("TempPref75")
                        .HasColumnType("double precision");

                    b.Property<double?>("TempPreferred")
                        .HasColumnType("double precision");

                    b.Property<string>("WestEastE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WestEastW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Westernmost")
                        .HasColumnType("double precision");

                    b.HasKey("StockCode");

                    b.ToTable("StockEnvironment");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.StockExternalRef", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("integer");

                    b.Property<string>("AFORO_ID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AusMuseum")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BOLD_ID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DORIS_ID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EcotoxID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EssayID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FIGIS_ID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FishSounds_ID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FishTrace")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FishipediaID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GMAD_ID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GenBankID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ICESStockID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IGFAName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MitoRef")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OsteoBaseID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RfeID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SAUP")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SAUP_Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SAUP_ID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SocotraAtlasID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StocksRefNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("StockCode");

                    b.ToTable("StockExternalRefs");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.StockMetadata", b =>
                {
                    b.Property<int>("StockCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEntered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Entered")
                        .HasColumnType("integer");

                    b.Property<int?>("Expert")
                        .HasColumnType("integer");

                    b.Property<int?>("Modified")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TS")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StockCode");

                    b.ToTable("StockMetadata");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.Associations", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Ecologies.Ecology", "Ecology")
                        .WithOne("Associations")
                        .HasForeignKey("FishDex.EFCore.Entity.Ecologies.Associations", "EcologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecology");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.CircadianBehavior", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Ecologies.Ecology", "Ecology")
                        .WithOne("CircadianBehavior")
                        .HasForeignKey("FishDex.EFCore.Entity.Ecologies.CircadianBehavior", "EcologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecology");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.FeedingAndDiet", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Ecologies.Ecology", "Ecology")
                        .WithOne("FeedingAndDiet")
                        .HasForeignKey("FishDex.EFCore.Entity.Ecologies.FeedingAndDiet", "EcologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecology");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.HabitatZone", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Ecologies.Ecology", "Ecology")
                        .WithOne("HabitatZone")
                        .HasForeignKey("FishDex.EFCore.Entity.Ecologies.HabitatZone", "EcologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecology");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.SpecialHabitat", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Ecologies.Ecology", "Ecology")
                        .WithOne("SpecialHabitat")
                        .HasForeignKey("FishDex.EFCore.Entity.Ecologies.SpecialHabitat", "EcologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecology");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.Substrate", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Ecologies.Ecology", "Ecology")
                        .WithOne("Substrate")
                        .HasForeignKey("FishDex.EFCore.Entity.Ecologies.Substrate", "EcologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecology");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecosystem.Ecosystem", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Ecosystem.EcosystemRef", "EcosystemRef")
                        .WithMany("Occurrences")
                        .HasForeignKey("E_CODE")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EcosystemRef");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Media.SystemImage", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Species.Species", null)
                        .WithMany("Pictures")
                        .HasForeignKey("SpecCode")
                        .HasPrincipalKey("SpecCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphData", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Stocks.Stock", null)
                        .WithOne()
                        .HasForeignKey("FishDex.EFCore.Entity.MorphData.MorphData", "StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphFins", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.MorphData.MorphData", "MorphData")
                        .WithOne("Fins")
                        .HasForeignKey("FishDex.EFCore.Entity.MorphData.MorphFins", "StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MorphData");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphMeristics", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.MorphData.MorphData", "MorphData")
                        .WithOne("Meristics")
                        .HasForeignKey("FishDex.EFCore.Entity.MorphData.MorphMeristics", "StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MorphData");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphMetrics", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.MorphData.MorphData", "MorphData")
                        .WithOne("Metrics")
                        .HasForeignKey("FishDex.EFCore.Entity.MorphData.MorphMetrics", "StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MorphData");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphPigmentation", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.MorphData.MorphData", "MorphData")
                        .WithOne("Pigmentation")
                        .HasForeignKey("FishDex.EFCore.Entity.MorphData.MorphPigmentation", "StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MorphData");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphTeeth", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.MorphData.MorphData", "MorphData")
                        .WithOne("Teeth")
                        .HasForeignKey("FishDex.EFCore.Entity.MorphData.MorphTeeth", "StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MorphData");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Species.CommonName", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Species.Species", "Species")
                        .WithMany("CommonNames")
                        .HasForeignKey("SpecCode")
                        .HasPrincipalKey("SpecCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Species.Genus", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Species.Family", null)
                        .WithMany("Genuses")
                        .HasForeignKey("FamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Species.Species", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Species.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FishDex.EFCore.Entity.Species.Genus", "Genus")
                        .WithMany("Species")
                        .HasForeignKey("GenusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Genus");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.Stock", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Species.Species", null)
                        .WithMany("Stocks")
                        .HasForeignKey("SpecCode")
                        .HasPrincipalKey("SpecCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.StockConservation", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Stocks.Stock", "Stock")
                        .WithOne("Conservation")
                        .HasForeignKey("FishDex.EFCore.Entity.Stocks.StockConservation", "StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.StockDataAvailability", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Stocks.Stock", "Stock")
                        .WithOne("DataFlags")
                        .HasForeignKey("FishDex.EFCore.Entity.Stocks.StockDataAvailability", "StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.StockEnvironment", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Stocks.Stock", "Stock")
                        .WithOne("Environment")
                        .HasForeignKey("FishDex.EFCore.Entity.Stocks.StockEnvironment", "StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.StockExternalRef", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Stocks.Stock", "Stock")
                        .WithOne("ExternalRefs")
                        .HasForeignKey("FishDex.EFCore.Entity.Stocks.StockExternalRef", "StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.StockMetadata", b =>
                {
                    b.HasOne("FishDex.EFCore.Entity.Stocks.Stock", "Stock")
                        .WithOne("Metadata")
                        .HasForeignKey("FishDex.EFCore.Entity.Stocks.StockMetadata", "StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecologies.Ecology", b =>
                {
                    b.Navigation("Associations");

                    b.Navigation("CircadianBehavior");

                    b.Navigation("FeedingAndDiet");

                    b.Navigation("HabitatZone");

                    b.Navigation("SpecialHabitat");

                    b.Navigation("Substrate");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Ecosystem.EcosystemRef", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.MorphData.MorphData", b =>
                {
                    b.Navigation("Fins");

                    b.Navigation("Meristics");

                    b.Navigation("Metrics");

                    b.Navigation("Pigmentation");

                    b.Navigation("Teeth");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Species.Family", b =>
                {
                    b.Navigation("Genuses");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Species.Genus", b =>
                {
                    b.Navigation("Species");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Species.Species", b =>
                {
                    b.Navigation("CommonNames");

                    b.Navigation("Pictures");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("FishDex.EFCore.Entity.Stocks.Stock", b =>
                {
                    b.Navigation("Conservation");

                    b.Navigation("DataFlags");

                    b.Navigation("Environment");

                    b.Navigation("ExternalRefs");

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
