// <auto-generated />
using System;
using AquaHome.EFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaHome.EFCore.Migrations
{
    [DbContext(typeof(AquaHomeDbContext))]
    [Migration("20260703085338_AddRoleQuota")]
    partial class AddRoleQuota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaHome.EFCore.Entity.Aquarium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("LengthCm")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Style")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WaterType")
                        .HasColumnType("integer");

                    b.Property<double?>("WidthCm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Aquariums");
                });

            modelBuilder.Entity("AquaHome.EFCore.Entity.AquariumFish", b =>
                {
                    b.Property<Guid>("AquariumId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpecCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("AquariumId", "SpecCode");

                    b.ToTable("AquariumFish");
                });

            modelBuilder.Entity("AquaHome.EFCore.Entity.AquariumMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AquariumId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.HasKey("Id");

                    b.HasIndex("AquariumId");

                    b.ToTable("AquariumMedia");
                });

            modelBuilder.Entity("AquaHome.EFCore.Entity.AquariumTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AquaTaskType")
                        .HasColumnType("integer");

                    b.Property<Guid>("AquariumId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("Reminded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AquariumId", "IsCompleted");

                    b.HasIndex("IsCompleted", "Reminded", "DueAt");

                    b.ToTable("AquariumTasks");
                });

            modelBuilder.Entity("AquaHome.EFCore.Entity.QuotaUsage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuotaType")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "QuotaType", "Day");

                    b.ToTable("QuotaUsages");
                });

            modelBuilder.Entity("AquaHome.EFCore.Entity.RecentlyViewed", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpecCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "SpecCode");

                    b.HasIndex("UserId", "ViewedAt");

                    b.ToTable("RecentlyViewed");
                });

            modelBuilder.Entity("AquaHome.EFCore.Entity.RoleQuota", b =>
                {
                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("AiQaPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("ImageSearchPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAquariums")
                        .HasColumnType("integer");

                    b.Property<int>("MaxFavorites")
                        .HasColumnType("integer");

                    b.Property<int>("SearchPerDay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Role");

                    b.ToTable("RoleQuotas");

                    b.HasData(
                        new
                        {
                            Role = "Guest",
                            AiQaPerDay = 3,
                            ImageSearchPerDay = 3,
                            MaxAquariums = 2,
                            MaxFavorites = 10,
                            SearchPerDay = 20,
                            UpdatedAt = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Role = "Member",
                            AiQaPerDay = 15,
                            ImageSearchPerDay = 20,
                            MaxAquariums = 10,
                            MaxFavorites = 100,
                            SearchPerDay = 115,
                            UpdatedAt = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Role = "ContentAdmin",
                            AiQaPerDay = -1,
                            ImageSearchPerDay = -1,
                            MaxAquariums = -1,
                            MaxFavorites = -1,
                            SearchPerDay = -1,
                            UpdatedAt = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Role = "SystemAdmin",
                            AiQaPerDay = -1,
                            ImageSearchPerDay = -1,
                            MaxAquariums = -1,
                            MaxFavorites = -1,
                            SearchPerDay = -1,
                            UpdatedAt = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AquaHome.EFCore.Entity.UserFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpecCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "SpecCode");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("AquaHome.EFCore.Entity.AquariumFish", b =>
                {
                    b.HasOne("AquaHome.EFCore.Entity.Aquarium", "Aquarium")
                        .WithMany("Fish")
                        .HasForeignKey("AquariumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aquarium");
                });

            modelBuilder.Entity("AquaHome.EFCore.Entity.AquariumMedia", b =>
                {
                    b.HasOne("AquaHome.EFCore.Entity.Aquarium", "Aquarium")
                        .WithMany()
                        .HasForeignKey("AquariumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aquarium");
                });

            modelBuilder.Entity("AquaHome.EFCore.Entity.AquariumTask", b =>
                {
                    b.HasOne("AquaHome.EFCore.Entity.Aquarium", "Aquarium")
                        .WithMany()
                        .HasForeignKey("AquariumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aquarium");
                });

            modelBuilder.Entity("AquaHome.EFCore.Entity.Aquarium", b =>
                {
                    b.Navigation("Fish");
                });
#pragma warning restore 612, 618
        }
    }
}
